# build environment
FROM node:10

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ENV NODE_PATH=./src

COPY package.json /usr/src/app/package.json

RUN npm install --silent

RUN npm install react-scripts@3.0.1 -g --silent

COPY . /usr/src/app

RUN npm run build

CMD [ "npm", "run" ,"production" ]